settings =
{
    {
      id=1,
      l=30,
      frame_max=1,
      path="res/Map/object/2/2.png"
    },
    {
      id=2,
      l=30,
      frame_max=3,
      anim_rat=0.2,
      path="res/Map/object/2/1/"
    },
    {
      id=3,
      l=45,
      frame_max=1,
      path="res/Map/object/2/3.png"
    },
    {
      id=4,
      l=45,
      frame_max=1,
      path="res/Map/object/2/22.png"
    },
    {
      id=5,
      l=25,
      frame_max=1,
      path="res/Map/object/2/7.png"
    },
    {
      id=6,
      l=25,
      frame_max=1,
      path="res/Map/object/2/11.png"
    },
    {
      id=7,
      l=25,
      frame_max=1,
      path="res/Map/object/2/12.png"
    },
    {
      id=8,
      l=25,
      frame_max=1,
      path="res/Map/object/2/8.png"
    },
    {
      id=9,
      l=25,
      frame_max=1,
      path="res/Map/object/2/9.png"
    },
}

return settings
